name: iOS CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fastlane
        run: |
          brew install fastlane

      - name: Run CI
        run: |
          fastlane ios ci
